---
name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libosmesa6-dev \
            mesa-utils \
            libsm6 \
            libxext6 \
            libxrender1

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.12.10'

      - name: Set up cache key
        run: |
          os_version=$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2)
          python_version="${{ steps.setup-python.outputs.python-version }}"
          python_location="${{ env.pythonLocation }}"
          cache_key="${python_version}-${os_version}-${python_location}"
          echo "cache_key=$cache_key" >> $GITHUB_ENV

      - name: Set up cache for installed packages
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.cache_key }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install --default-timeout=100 --retries=5 -r requirements-ci.txt

      - name: Install project package in editable mode
        run: |
          pip install -e .

      - name: Lint with ruff
        run: ruff check --output-format=github --line-length 79

      - name: Run mypy
        run: |
          mypy \
          --install-types \
          --non-interactive \
          --ignore-missing-imports \
          --disallow-untyped-defs \
          .

      - name: YAML Lint
        run: yamllint --strict .

      - name: Run tests with coverage
        run: pytest --cov -n auto --maxfail=2 --disable-warnings
