---
name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libosmesa6-dev \
            mesa-utils \
            libsm6 \
            libxext6 \
            libxrender1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up cache for installed packages
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-ci.txt') }}

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=100 --retries=5 -r requirements-ci.txt

      - name: Check OpenCV installation
        run: |
          python -c "import cv2; print('OpenCV version:', cv2.__version__)"

      - name: Lint with ruff
        run: ruff check --output-format=github --line-length 79

      - name: Run mypy
        run: |
          mypy \
          --ignore-missing-imports \
          --disallow-untyped-defs \
          --strict-optional \
          --warn-unused-ignores \
          --disable-error-code type-arg \
          .

      - name: YAML Lint
        run: yamllint --strict .

      - name: Uninstall OpenCV and install headless version for tests
        run: |
          pip uninstall -y opencv-python
          pip install opencv-python-headless

      - name: Run tests with coverage
        run: |
          coverage run -m pytest --maxfail=2 --disable-warnings tests/
          coverage report
