---
name: Code Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with ruff
        run: ruff check --output-format=github --line-length 79

      - name: Run mypy
        run: |
          mypy \
          --ignore-missing-imports \
          --disallow-untyped-defs \
          --strict-optional \
          --warn-unused-ignores \
          --disable-error-code type-arg \
          .

      - name: YAML Lint
        run: yamllint --strict --exclude .github/workflows .
