---
name: Test Release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
            image: "python:3.10-slim"
          - version: "3.11"
            image: "python:3.11-slim"
          - version: "3.12"
            image: "python:3.12-slim"
    container:
      image: ${{ matrix.python.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            git \
            build-essential \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libosmesa6-dev \
            mesa-utils \
            libsm6 \
            libxext6 \
            libxrender1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=100 --retries=5 -r requirements-ci.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest --maxfail=2 --disable-warnings tests/
          coverage report
