---
# Parameters for a Collective Thrust and Body Rates (CTBR) controller

ctbr_controller_params:
  dt: 0.04  # Controller frequency 25 Hz [s]
  pid_coefficients:  # P, I, D coefficients for each rate controller
    - [10.0, 0.0, 0.1]  # Roll rate
    - [10.0, 0.0, 0.1]  # Pitch rate
    - [10.0, 0.0, 0.1]  # Yaw rate
