---
# Parameters for a Collective Thrust and Body Rates (CTBR) controller

ctbr_controller_params:
  # P, I, D gains for rate controllers
  rate_pid_gains:
    - [10.0, 0.0, 0.1]  # Roll rate
    - [10.0, 0.0, 0.1]  # Pitch rate
    - [10.0, 0.0, 0.1]  # Yaw rate
